### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by SunboX**
reworked the whole menu component

### CODE REVIEW

**Comment by partikule** [comment]
This menu generate DIVs, isn't it ?

A menu should be build with UL > LI, why make it more complex with divs ?

**Comment by SunboX** [comment]
This is an Application Framework, no Web-Page. It will not be useable by screenreaders at all. So no need to use ul, li, aso. HTML lists are terrible, you have to reset all default styling. Div has no initial styling. And you don't need links (a-tags). Links are bad, you have to remove te default styling too plus you have to prevent the default behavior. Div tags do nothing by default, like a blank canvas.

Greetings André

**Comment by partikule** [comment]
Sure about the web page, I totally agree.

I disagree on other arguments. In your way, why not use DL, or SPAN, or STRONG... EMs are quite nice...
Using divs is like disagree with the work of the W3C and make it more unreadable just because it look easier. The 1990's aren't so far...Why not a panel in a table ?
The style of LI can be globally (aren't they ?) disabled by a reset CSS declaration. 
You don't need to add anchors inside li, just styling them to fit your need and add the event on it.

**Comment by SunboX** [comment]
Hm, i like Div´s. ;o) Others, too. This is how a facebook connection-list looks like:

```
<div class="connections">
    <span class="total total_plus hidden_elem">...</span>
    <span class="total">...</span>
    <div class="connections_grid clearfix">
        <div class="grid_item"><a href="" target="_blank"><img class="img" src="..."><div class="name"></div></a></div>
        <div class="grid_item"><a href="" target="_blank"><img class="img" src="..."><div class="name"></div></a></div>
        <div class="grid_item"><a href="" target="_blank"><img class="img" src="..."><div class="name"></div></a></div>
        <div class="grid_item"><a href="" target="_blank"><img class="img" src="..."><div class="name"></div></a></div>
        <div class="grid_item"><a href="" target="_blank"><img class="img" src="..."><div class="name"></div></a></div>
        <div class="grid_item"><a href="" target="_blank"><img class="img" src="..."><div class="name"></div></a></div>
        ...
    </div>
</div>
```

**Comment by partikule** [comment]
Hmm.... I like EMs, not a reason to break a nice thing...
About FB : Did you had a look at the "I like it" widget produced code ?
They use tables to design it !
Youhouuu ! Have a beer, the 1990's are back ! 
More seriously, Facebook is perhaps a business success story, but certainly not a "coding good practice' reference.

I'm surprised that with your skill level you introduce such things just "because you like it".
Styling an UL / LI is easy and if you don't like them, you can use DL... if the use of DD is justified.
http://www.noupe.com/css/css-styled-lists-20-demos-tutorials-and-best-of.html

It could make more sense to optimize the exiting CSS and why not, to make the MochaUI init more easy and consistent, the core more simple to understand by writing a doc of dependencies..., write some tutos or examples, answer to the issues on Git... instead of make a soup from things which were nice.

Hope I don't hurt you, it's really not the purpose. I like Mocha, and I hope it goes the good way...
"Less is More" !

**Comment by toopixel** [comment]
I am joining Partikule's comment here, using DIV's is a non-sens in a menu situation !

**Comment by SunboX** [comment]
Ok, you are right. So fork it and make it better. That was what I wanted to do. I'm not perfect, I offer my spare time to make things better that I like. And I do it the way I like. Otherwise I wouldn't do it. But I have no problem with other solutions. You like/want list elements, no problem. Fork it. ;o)

**Comment by toopixel** [comment]
hmmm that's not really an expected reaction from someone which is supposed to be a reference in his domain, seems you are very closed to what other think, but more than opinions, it's not the problem here, the real problem is that you are doing it wrong regarding web standards, it's not me or Partikule which invented standards, it's W3C and YOU and everyone should developp following those standards, whenever you do things by passion or beeing paid for it.

Truely, the solution may be to fork it in order to "save MochaUI".................................

Good luck.

**Comment by toopixel** [comment]
Wanted to add that tonight, you made me hate your project because of such bad reactions from the main developper that you are. MochaUI is project which I support and love for some years regarding what the past coder did on it, really amazing work with great mentality behind the project. That's very sad for me to read your reactions, and probably for many other people which are using MochaUI. Once more, good luck with your project.

**Comment by SunboX** [comment]
I'm not the main developer! I'm just someone like you.

**Comment by partikule** [comment]
The project is more than good it is very good and we cannot say we hate it. Not possible.
We simply wish that Mocha stays alive and more than that, that it will adopted widely, not only by few developpers but why not that it becomes a part of the future mootools UI  libraries...

We can of course fork it and bring the menu back to standard, but that will just add one more fork for a project which does not have so much watchers currently. What will it mean ? That all developper who comes to the project forks Mocha to change a litlle thing and finally, we will have dozen of Mochas and the users we are will not be able to choose one of them... A big soup, in fact. But thta's not the point, we're speaking about a pull requests on the main project, not about forks.

So I'm very happy than developpers like you get involved in this project, it's important for the project surviving. What's also important is to respect standards, even on small things and even you personnaly disagree with them. In 1997, I was developping websites with beautiful tables, tr, td... like many others. 2 years later, I learned more about standards and I saw I was on the wrong way. I'm not telling you you are on the wrong way, I just hope our comments will let you consider your choice regarding this pull request.

To finish, MochaUI has today certainly other more important open topics than the main menu : I see alot of developpers around Mocha, but where is the user's voice ? 

What's today missing, after the big refactor Chris do, is a user oriented documentation, which answers the main questions - without the need of a deep code analyse - like :
- How should I start Mocha ? Why do I need some CSS and not some others, which are loaded automaticaly ?
- What's the best way to instanciate a new Window ? "Create" or "New..." What's the difference between them ?
- What are dependecies between classes and how did they work together ?

Even the provided examples are great, they aren't enoug to understand Mocha. A "good practice" user-guide and a real users community around the project will be welcome.

"You can long work on a system, if nobody use it, you just work alone and for nothing."

**Comment by SunboX** [comment]
@partikule

Good statement! It was late last night, so excuse me. ;o) I know Chris is cleaning up/rewriting my menu component code (like he did for the stepper component). There are more necessary things to do, like avoiding using lot of classes/function calls. Maybe Chris changes also the Div´s to list elements. If not and I have the time, I will change it later.

But I don´t think it´s bad, if other developers fork MochaUI and try to make it better. Not all will go into the main project. You can see on the PhoneGap project, that this kind of programming (community driven) works really good.

greetings André (no main developer ;o))

**Comment by toopixel** [comment]
Good to read that SunboX ;)

**Comment by partikule** [comment]
yes... it was late yesterday... :-)

**Comment by cdotyone** [comment]
Cool it guys,  the menu has not been committed to the branch it was just a submission. I appreciate everyone's interest.  Regardless of DIV or UL, the menus look great, and I can tell SunboX put some effort into it.  It has not been excepted but for other reasons.  SunboX nonetheless gave me a great starting point.  I will keep all of your point of views in mind as I take the submission he has made and put a Mocha spin on it.   I personally prefer UL/LI for menus, but this is just a pattern I am used to.
-Chris (the current main developer) :)

**Pull request closed without merging**
