### PR TITLE
id management on menu items

### PR DESCRIPTION
**Pull request by altairis-tof**
hello, i'm using mochaui to develop an ihm for a web app.
here is my first contrib which consists in giving an id to menu items.

### CODE REVIEW

**Comment by altairis-tof** [comment]
another commit to avoid problem with IE8

**Comment by partikule** [comment]
oups... sorry Dimitar...

**Comment by cdotyone** [comment]
Current development branch should not be passing negative values anymore.

**Comment by cdotyone** [comment]
id management on menu items added - 
mootools lib change not added.
-Chris

**Pull request closed without merging**
